import 'dart:async';import 'dart:convert';import 'package:equatable/equatable.dart';import 'package:flutter_bloc/flutter_bloc.dart';import 'package:locallink/core/bloc/bloc_utils.dart';import 'package:locallink/core/models/device.dart';import 'package:locallink/core/models/group.dart';import 'package:locallink/features/home/domain/home_repository_contract.dart';
final class HomeState extends Equatable{final List<Device> devices;final List<LocalGroup> groups;final bool loading;final String? error;const HomeState({this.devices=const [],this.groups=const [],this.loading=true,this.error});HomeState copyWith({List<Device>? devices,List<LocalGroup>? groups,bool? loading,String? error,bool clearError=false})=>HomeState(devices:devices??this.devices,groups:groups??this.groups,loading:loading??this.loading,error:clearError?null:(error??this.error));@override List<Object?>get props=>[devices,groups,loading,error];}
final class HomeBloc extends Cubit<HomeState>{
 final HomeRepositoryContract repository;
 StreamSubscription<Map<String,dynamic>>? _presenceSub,_directPresenceSub;
 Timer? _statusTimer;bool _started=false;
 HomeBloc({required this.repository}):super(const HomeState());
 List<Device> get devices=>state.devices;List<LocalGroup> get groups=>state.groups;bool get loading=>state.loading;String? get error=>state.error;
 void start(){if(_started)return;_started=true;_presenceSub=repository.presenceEvents.listen(_onPresence);_directPresenceSub=repository.directPresenceEvents.listen(_onDirectPresence);_statusTimer=Timer.periodic(const Duration(seconds:10),(_)=>expireStalePresence());unawaited(load());}
 Future<void> load()async{emit(state.copyWith(loading:true));try{final devices=await repository.devices();final groups=await repository.groups();for(final d in devices)await repository.cacheDevice(d);emit(state.copyWith(devices:devices.where((d)=>d.id!=repository.localDeviceId).toList(),groups:groups,loading:false,clearError:true));}catch(e){emit(state.copyWith(devices:(await repository.localDevices()).where((d)=>d.id!=repository.localDeviceId).toList(),groups:await repository.localGroups(),error:cleanBlocError(e),loading:false));}}
 Future<LocalGroup?> createGroup(String name,List<String> memberIds)async{try{final g=await repository.createGroup(name,memberIds);emit(state.copyWith(groups:[...state.groups,g],clearError:true));return g;}catch(e){emit(state.copyWith(error:cleanBlocError(e)));return null;}}
 void _onDirectPresence(Map<String,dynamic> event){final raw=event['payload']?.toString();if(raw==null||raw.isEmpty)return;try{final data=jsonDecode(raw) as Map<String,dynamic>;if(data['type']?.toString()!='direct_presence')return;final server=data['server_connected']==true;final wifi=data['wifi_direct_connected']==true;_onPresence({'device_id':data['sender_id'],'network_status':wifi?'orange':server?'green':'red','server_connected':server,'wifi_direct_connected':wifi,'status_updated_at':data['status_updated_at']?.toString()??''});}catch(_){}}
 void _onPresence(Map<String,dynamic> e){final id=e['device_id']?.toString();if(id==null||id.isEmpty)return;final current=(state.devices.where((d)=>d.id==id).isEmpty?null:state.devices.firstWhere((d)=>d.id==id))??Device.fromJson({'id':id,'name':e['name']?.toString()??'Nearby device','platform':e['platform']?.toString()??'android','created_at':e['created_at']?.toString()??'','last_seen_at':e['last_seen_at']?.toString()??''});final updated=Device.fromJson({'id':current.id,'name':current.name,'platform':current.platform,'created_at':current.createdAt,'last_seen_at':e['last_seen_at']?.toString()??current.lastSeenAt,'network_status':e['network_status'],'server_connected':e['server_connected']==true,'wifi_direct_connected':e['wifi_direct_connected']==true,'status_updated_at':e['status_updated_at']?.toString()??''});unawaited(repository.cacheDevice(updated));final next=[...state.devices];final i=next.indexWhere((d)=>d.id==id);if(i<0)next.add(updated);else next[i]=updated;emit(state.copyWith(devices:next));}
 void expireStalePresence(){final now=DateTime.now().toUtc();var changed=false;final next=state.devices.map((d){final stamp=DateTime.tryParse(d.statusUpdatedAt)?.toUtc();if(stamp==null||now.difference(stamp)<=const Duration(seconds:40)||d.networkStatus==DeviceNetworkStatus.unknown)return d;changed=true;final x=Device.fromJson({'id':d.id,'name':d.name,'platform':d.platform,'created_at':d.createdAt,'last_seen_at':d.lastSeenAt,'network_status':'unknown','server_connected':false,'wifi_direct_connected':false,'status_updated_at':d.statusUpdatedAt});unawaited(repository.cacheDevice(x));return x;}).toList();if(changed)emit(state.copyWith(devices:next));}
 @override Future<void> close()async{_statusTimer?.cancel();await _presenceSub?.cancel();await _directPresenceSub?.cancel();return super.close();}
}
