import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:locallink/features/admin/bloc/admin_bloc.dart';

class AdminSettingsScreen extends StatefulWidget { const AdminSettingsScreen({super.key}); @override State<AdminSettingsScreen> createState()=>_AdminSettingsScreenState(); }
class _AdminSettingsScreenState extends State<AdminSettingsScreen>{
  late final TextEditingController _refresh=TextEditingController();
  late final TextEditingController _alerts=TextEditingController();
  bool _seeded=false;
  @override void dispose(){_refresh.dispose();_alerts.dispose();super.dispose();}
  Future<void> _save() async {final refresh=int.tryParse(_refresh.text);final alerts=int.tryParse(_alerts.text);if(refresh==null||alerts==null){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter valid numeric settings.')));return;}await context.read<AdminBloc>().updateSettings(dashboardRefreshSeconds:refresh,securityAlertThreshold:alerts);if(!mounted)return;final error=context.read<AdminBloc>().state.error;ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(error==null?'Admin settings updated.':'Failed to update settings: $error')));}
  @override Widget build(BuildContext context)=>BlocBuilder<AdminBloc,AdminState>(builder:(context,state){final s=state.settingsData??const {};if(!_seeded && state.settingsData != null){_refresh.text='${s['dashboard_refresh_seconds']??15}';_alerts.text='${s['security_alert_threshold']??1}';_seeded=true;}return ListView(padding:const EdgeInsets.all(16),children:[const Text('Admin Settings',style:TextStyle(fontSize:22,fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('Only safe Admin Panel preferences are mutable here. Core server limits remain controlled by deployment configuration.'),const SizedBox(height:16),TextField(controller:_refresh,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Dashboard refresh (5–120 seconds)')),const SizedBox(height:12),TextField(controller:_alerts,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Security alert threshold')),const SizedBox(height:16),FilledButton.icon(onPressed:_save,icon:const Icon(Icons.save_outlined),label:const Text('Save settings')),const SizedBox(height:20),Card(child:ListTile(leading:const Icon(Icons.info_outline),title:Text('Server configuration is ${s['read_only_server_config']==true?'read-only':'mutable'}'),subtitle:const Text('Environment-backed TLS, storage and request limits are not silently modified by the Admin Panel.'))),Card(child:ListTile(leading:const Icon(Icons.backup_outlined),title:const Text('Database backup'),subtitle:const Text('Create an audited database backup using the existing protected backup endpoint.'),trailing:IconButton(onPressed:() async { final result=await context.read<AdminBloc>().backup(); if(context.mounted && result!=null){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Backup created: ${result['file']??''}')));} },icon:const Icon(Icons.play_arrow))))]);});
}
