import 'package:equatable/equatable.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:locallink/core/bloc/bloc_utils.dart';
import 'package:locallink/features/authentication/data/models/authentication_models.dart';
import 'package:locallink/features/authentication/domain/authentication_repository_contract.dart';
import 'package:locallink/features/connectivity/data/models/discovered_server.dart';

final class AuthenticationState extends Equatable {
  final bool registerMode, busy, discovering, trustedServer;
  final String? error, serverIdentityError;
  final List<DiscoveredServer> servers;
  final PairingInfo? pairingInfo;
  const AuthenticationState({this.registerMode=true,this.busy=false,this.discovering=false,this.trustedServer=false,this.error,this.serverIdentityError,this.servers=const [],this.pairingInfo});
  AuthenticationState copyWith({bool? registerMode,bool? busy,bool? discovering,bool? trustedServer,String? error, bool clearError=false,String? serverIdentityError,bool clearServerIdentityError=false,List<DiscoveredServer>? servers,PairingInfo? pairingInfo,bool clearPairingInfo=false})=>AuthenticationState(registerMode:registerMode??this.registerMode,busy:busy??this.busy,discovering:discovering??this.discovering,trustedServer:trustedServer??this.trustedServer,error:clearError?null:(error??this.error),serverIdentityError:clearServerIdentityError?null:(serverIdentityError??this.serverIdentityError),servers:servers??this.servers,pairingInfo:clearPairingInfo?null:(pairingInfo??this.pairingInfo));
  @override List<Object?> get props=>[registerMode,busy,discovering,trustedServer,error,serverIdentityError,servers,pairingInfo];
}
final class AuthenticationBloc extends Cubit<AuthenticationState>{
  final AuthenticationRepositoryContract repository;
  AuthenticationBloc(this.repository,{bool registerMode=true}):super(AuthenticationState(registerMode:registerMode));
  bool get registerMode=>state.registerMode; bool get busy=>state.busy; bool get discovering=>state.discovering; String? get error=>state.error; List<DiscoveredServer> get servers=>state.servers; PairingInfo? get pairingInfo=>state.pairingInfo; bool get trustedServer=>state.trustedServer; String? get serverIdentityError=>state.serverIdentityError;
  void setRegisterMode(bool value){if(state.busy||state.registerMode==value)return;emit(state.copyWith(registerMode:value,clearError:true));}
  void clearError(){if(state.error!=null)emit(state.copyWith(clearError:true));}
  Future<List<DiscoveredServer>> discoverServers({required String currentAddress,required String deviceName}) async{if(state.discovering)return state.servers;emit(state.copyWith(discovering:true,clearError:true));try{final servers=await repository.discoverServers();emit(state.copyWith(servers:servers));if(servers.isEmpty){emit(state.copyWith(error:'No LocalLink server found. Make sure the laptop and phone are on the same private Wi-Fi network and the backend is running.'));return servers;}final selected=currentAddress.trim();final address=selected.isNotEmpty&&servers.any((s)=>s.address==selected)?selected:servers.first.address;await loadPairingInfo(address:address,deviceName:deviceName);return servers;}catch(error){emit(state.copyWith(error:'Discovery failed: $error'));return state.servers;}finally{emit(state.copyWith(discovering:false));}}
  Future<void> loadPairingInfo({required String address,required String deviceName}) async{final trimmed=address.trim();if(trimmed.isEmpty){emit(state.copyWith(error:'Enter a LocalLink server address first.'));return;}emit(state.copyWith(clearError:true));try{final info=await repository.verifyServer(address:trimmed,deviceName:deviceName);emit(state.copyWith(pairingInfo:info,trustedServer:repository.isServerTrusted(info),serverIdentityError:repository.serverIdentityError(info),clearServerIdentityError:repository.serverIdentityError(info)==null));}catch(error){emit(state.copyWith(clearPairingInfo:true,trustedServer:false,serverIdentityError:'Could not verify LocalLink server identity: $error'));}}
  void clearServerVerification(){if(state.pairingInfo==null && state.serverIdentityError==null && state.trustedServer==false)return;emit(state.copyWith(clearPairingInfo:true,trustedServer:false,clearServerIdentityError:true,clearError:true));}
  Future<void> trustCurrentServer() async{final info=state.pairingInfo;if(info==null||info.serverId.isEmpty||info.fingerprint.isEmpty)return;await repository.trustServer(info);emit(state.copyWith(trustedServer:true,clearServerIdentityError:true,clearError:true));}
  Future<AuthResult> submit({required String server,required String deviceName,required String username,required String password,String? pairingCode}) async{final s=server.trim(),name=deviceName.trim(),u=username.trim().toLowerCase();if(s.isEmpty||name.isEmpty||u.isEmpty||password.isEmpty)throw _validation('Enter the server, device name, username, and password.');if(u.length<3||!RegExp(r'^[a-z0-9_][a-z0-9_.-]{2,31}$').hasMatch(u))throw _validation('Username must be 3–32 characters and use letters, numbers, dot, dash, or underscore.');if(state.registerMode&&password.length<8)throw _validation('Password must be at least 8 characters.');final normalized=repository.normalizeServerAddress(s);if(state.pairingInfo==null||repository.serverAddress!=normalized)await loadPairingInfo(address:normalized,deviceName:name);if(state.pairingInfo==null)throw _validation('The LocalLink server could not be verified.');if(!state.trustedServer)throw _validation('Trust the verified LocalLink server before continuing.');emit(state.copyWith(busy:true,clearError:true));try{return state.registerMode?await repository.register(username:u,password:password,deviceName:name,pairingCode:pairingCode):await repository.login(username:u,password:password,deviceName:name,pairingCode:pairingCode);}catch(error){emit(state.copyWith(error:cleanBlocError(error)));rethrow;}finally{emit(state.copyWith(busy:false));}}
  Exception _validation(String message){emit(state.copyWith(error:message));return Exception(message);}
}
